automoviles/applications/coche/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "coche_app"

urlpatterns = [
    path('lista-coches/', views.ListCochesListView.as_view(), name="list_coches"),
    path('registrar-coche/', views.CocheCreateView.as_view(), name="regist_coches"),
    path('editar-coche/<pk>/', views.CocheUpdateView.as_view(), name="edit_coches"),
    path('eliminar-coche/<pk>/', views.CocheDeleteView.as_view(), name="delete_coches"),
]

automoviles/applications/marca/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "marca_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name="inicio"),
    path('lista-marcas/', views.ListMarcasListView.as_view(), name="list_marcas"),
    path('registrar-marca/', views.MarcaCreateView.as_view(), name="regist_marcas"),
    path('editar-marca/<pk>/', views.MarcaUpdateView.as_view(), name="edit_marcas"),
    path('eliminar-marca/<pk>/', views.MarcaDeleteView.as_view(), name="delete_marcas"),
]

automoviles/applications/modelo/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "modelo_app"

urlpatterns = [
    path('lista-modelos/', views.ListModelosListView.as_view(), name="list_modelos"),
    path('registrar-modelo/', views.ModeloCreateView.as_view(), name="regist_modelos"),
    path('editar-modelo/<pk>/', views.ModeloUpdateView.as_view(), name="edit_modelos"),
    path('eliminar-modelo/<pk>/', views.ModeloDeleteView.as_view(), name="delete_modelos"),
]

automoviles/automoviles/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLS APPs
    re_path('', include('applications.marca.urls')),
    re_path('', include('applications.modelo.urls')),
    re_path('', include('applications.coche.urls'))
]

automoviles/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Automoviles</li>
        <li>
          <a href="">Listar</a>
          <ul class="menu vertical">
            <li><a href="{% url 'marca_app:list_marcas' %}">Marcas</a></li>
            <li><a href="{% url 'modelo_app:list_modelos' %}">Modelos</a></li>
            <li><a href="{% url 'coche_app:list_coches' %}">Coches</a></li>
          </ul>
        </li>
        <li>
          <a href="">Registrar</a>
          <ul class="menu vertical">
            <li><a href="{% url 'marca_app:regist_marcas' %}">Marcas</a></li>
            <li><a href="{% url 'modelo_app:regist_modelos' %}">Modelos</a></li>
            <li><a href="{% url 'coche_app:regist_coches' %}">Coches</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>