automoviles/applications/modelo/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "modelo_app"

urlpatterns = [
    path('lista-modelos/', views.ListModelosListView.as_view(), name="list_modelos"),
    path('registrar-modelo/', views.ModeloCreateView.as_view(), name="regist_modelos"),
    path('editar-modelo/<pk>/', views.ModeloUpdateView.as_view(), name="edit_modelos"),
    path('eliminar-modelo/<pk>/', views.ModeloDeleteView.as_view(), name="delete_modelos"),
]

automoviles/automoviles/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLS APPs
    re_path('', include('applications.marca.urls')),
    re_path('', include('applications.modelo.urls')),
    re_path('', include('applications.coche.urls'))
]

automoviles/applications/modelo/models.py
from django.db import models
from .managers import ModeloManager

class Modelo(models.Model):
    CARROCERIA_CHOICES=(
            ('0', 'Sedán'),
            ('1', 'Familiar'),
            ('2', 'Coupé'),
            ('3', 'Todoterreno'),
            ('4', 'Descapotable'),
            ('5', 'SUV'),
        )

    nombre = models.CharField('Modelo', max_length=50, unique=True)
    carroceria = models.CharField('Carroceria', max_length=1, choices=CARROCERIA_CHOICES)
    marca = models.ForeignKey('marca.Marca', verbose_name=("Marca"), on_delete=models.SET_NULL, blank=True, null=True)
    coches = models.ManyToManyField('coche.Coche', verbose_name=("Coches"), related_name='coche', blank=True)
    
    objects = ModeloManager()

    class Meta:
        verbose_name = 'Modelo'
        verbose_name_plural = 'Modelos'
        ordering = ['id']

    def __str__(self):
        return self.nombre

    def get_coches(self):
        return " - ".join([str(p) for p in self.coches.all()])

    def get_carroceria(self, key):
        return self.CARROCERIA_CHOICES(key)

automoviles/applications/modelo/forms.py
from django import forms

from .models import Modelo

class ModeloForm(forms.ModelForm):
    
    class Meta:
        model = Modelo
        fields = (
            'nombre',
            'carroceria',
            'marca',
            'coches',
        )
        widgets = {
            'carroceria': forms.Select(),
            'marca': forms.Select(),
            'coches': forms.SelectMultiple(),
        }

automoviles/applications/modelo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from .models import Modelo
from .forms import ModeloForm

#LIST
class ListModelosListView(ListView):
    context_object_name = 'lista_modelos'
    template_name = 'modelo/lista.html'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        return Modelo.objects.listar_modelos(palabra_clave)

#REGISTER
class ModeloCreateView(CreateView):
    model = Modelo
    template_name = "modelo/register.html"
    form_class = ModeloForm
    success_url = reverse_lazy('modelo_app:list_modelos')

    def form_valid(self, form):
        modelo = form.save()
        modelo.save()
        return super(ModeloCreateView, self).form_valid(form)

#UPDATE
class ModeloUpdateView(UpdateView):
    model = Modelo
    template_name = "modelo/editar.html"
    fields = [
        'nombre',
        'carroceria',
        'marca',
        'coches',
    ]
    success_url = reverse_lazy('modelo_app:list_modelos')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        #request.POST['name']
        return super().post(request, *args, **kwargs)

#DELETE
class ModeloDeleteView(DeleteView):
    model = Modelo
    template_name = "modelo/delete.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = reverse_lazy('modelo_app:list_modelos')
        self.object.delete()
        return HttpResponseRedirect(success_url)

automoviles/templates/modelo/delete.html
{% extends 'base.html' %}

{% block title %}Eliminar Modelo{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Eliminar Modelo {{object.nombre}}</h1>
            <div class="cell">
                <form class="cell" method="POST">{% csrf_token %}
                    <div class="callout secondary">
                        <h5>¿Desea eliminar este modelo?</h5>
                        <button type="submit" class="alert button">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}

automoviles/templates/modelo/editar.html
{% extends 'base.html' %}

{% block title %}Editar Modelo{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Editar Modelo</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                    <div class="medium-6 cell">
                        <label>Modelo:
                          {{form.nombre}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Marca:
                          {{form.marca}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Carroceria:
                          {{form.carroceria}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Coches:
                          {{form.coches}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="submit success button">Actualizar</button>
                    </div>
                </form>                
            </div>
        </div>
    </div>
    
{% endblock content %}

automoviles/templates/modelo/lista.html
{% extends 'base.html' %}

{% block title %}Lista Modelos{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Lista de Modelos</h1>
            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" id="kword" name="kword" placeholder="Buscar Modelo">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="50">ID</th>
                        <th width="150">MODELO</th>
                        <th width="150">CARROCERIA</th>
                        <th width="150">MARCA</th>
                        <th width="150">COCHES</th>
                        <th width="10"></th>
                        <th width="10"></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for m in lista_modelos %}
                            <tr>
                                <td>{{m.id}}</td>
                                <td>{{m.nombre}}</td>
                                <td>{{m.carroceria}}</td>
                                <td>{{m.marca}}</td>
                                <td>{{m.get_coches}}</td>
                                <td><a class="button warning" href="{% url 'modelo_app:edit_modelos' m.id %}">Editar</a></td>
                                <td><a class="alert button" href="{% url 'modelo_app:delete_modelos' m.id %}">Eliminar</a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>

            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                            </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                            {% ifequal pagina page_obj.number %}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                            {% endifequal%}
                            
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                  </nav>
                {% endif %}
            </div>

        </div>
    </div>


{% endblock content%}

automoviles/templates/modelo/register.html
{% extends 'base.html' %}

{% block title %}Registrar Modelo{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Registrar nuevo Modelo {{object.name}}</h1>
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Modelo:
                      {{form.nombre}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Marca:
                      {{form.marca}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Carroceria:
                      {{form.carroceria}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Coches:
                      {{form.coches}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="submit success button">Registrar</button>
                </div>
                
            </form>
        </div>
    </div>
</div>
    
{% endblock content %}