automoviles/applications/coche/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "coche_app"

urlpatterns = [
    path('lista-coches/', views.ListCochesListView.as_view(), name="list_coches"),
    path('registrar-coche/', views.CocheCreateView.as_view(), name="regist_coches"),
    path('editar-coche/<pk>/', views.CocheUpdateView.as_view(), name="edit_coches"),
    path('eliminar-coche/<pk>/', views.CocheDeleteView.as_view(), name="delete_coches"),
]

automoviles/automoviles/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLS APPs
    re_path('', include('applications.marca.urls')),
    re_path('', include('applications.modelo.urls')),
    re_path('', include('applications.coche.urls'))
]

automoviles/applications/coche/models.py
from django.db import models
from .managers import CocheManager

class Coche(models.Model):
    matricula = models.CharField('Matricula', max_length=7, unique=True)
    fecha_creacion = models.DateField('Fecha Creacion')
    modelo = models.ForeignKey('modelo.Modelo', verbose_name=("Modelo"), on_delete=models.SET_NULL, null=True)
    marca = models.ForeignKey('marca.Marca', verbose_name=("Marca"), on_delete=models.SET_NULL, null=True)

    objects = CocheManager()

    class Meta:
        verbose_name = 'Coche'
        verbose_name_plural = 'Coches'
        ordering = ['id']

    def __str__(self):
        return self.matricula

automoviles/applications/coche/forms.py
from django import forms

from .models import Coche

class CocheForm(forms.ModelForm):
    
    class Meta:
        model = Coche
        fields = (
            'matricula',
            'fecha_creacion',
            'marca',
            'modelo'
        )
        widgets = {
            'modelos': forms.Select(),
            'marca': forms.Select(),
            'fecha_creacion': forms.DateInput(
                attrs= {
                    'placeholder': 'Dia/Mes/Año',
                }
            )
        }

automoviles/applications/coche/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from .models import Coche
from .forms import CocheForm

# Create your views here.
class ListCochesListView(ListView):
    context_object_name = 'lista_coches'
    template_name = 'coche/lista.html'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        if palabra_clave == '':
            return Coche.objects.listar_coches()
        else:
            return Coche.objects.listar_coches_kword(palabra_clave)

class CocheCreateView(CreateView):
    model = Coche
    template_name = "coche/register.html"
    form_class = CocheForm
    success_url = reverse_lazy('coche_app:list_coches')

    def form_valid(self, form):
        modelo = form.save()
        modelo.save()
        return super(CocheCreateView, self).form_valid(form)

#UPDATE
class CocheUpdateView(UpdateView):
    model = Coche
    template_name = "coche/editar.html"
    fields = [
        'matricula',
        'fecha_creacion',
        'marca',
        'modelo',
    ]
    success_url = reverse_lazy('coche_app:list_coches')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        #request.POST['name']
        return super().post(request, *args, **kwargs)

#DELETE
class CocheDeleteView(DeleteView):
    model = Coche
    template_name = "coche/delete.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = reverse_lazy('coche_app:list_coches')
        self.object.delete()
        return HttpResponseRedirect(success_url)

automoviles/templates/coche/delete.html
{% extends 'base.html' %}

{% block title %}Eliminar Coche{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Eliminar Coche {{object.matricula}}</h1>
            <div class="cell">
                <form class="cell" method="POST">{% csrf_token %}
                    <div class="callout secondary">
                        <h5>¿Desea eliminar este coche?</h5>
                        <button type="submit" class="alert button">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}

automoviles/templates/coche/editar.html
{% extends 'base.html' %}

{% block title %}Editar Coche{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container"  style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Editar Coche</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                    <div class="medium-6 cell">
                        <label>Matricula:
                          {{form.matricula}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Fecha Fabricación:
                          {{form.fecha_creacion}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Marca:
                          {{form.marca}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Modelo:
                          {{form.modelo}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="submit success button">Actualizar</button>
                    </div>
                </form>                
            </div>
        </div>
    </div>
    
{% endblock content %}

automoviles/templates/coche/lista.html
{% extends 'base.html' %}

{% block title %}Lista Coches{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container"  style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Lista de Coches</h1>
            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" id="kword" name="kword" placeholder="Buscar Marca">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="50">MATRICULA</th>
                        <th width="150">MARCA</th>
                        <th width="150">MODELO</th>
                        <th width="150">FECHA CREACION</th>
                        <th width="10"></th>
                        <th width="10"></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for c in lista_coches %}
                            <tr>
                                <td>{{c.matricula}}</td>
                                <td>{{c.marca}}</td>
                                <td>{{c.modelo}}</td>
                                <td>{{c.fecha_creacion}}</td>
                                <td><a class="button warning" href="{% url 'coche_app:edit_coches' c.id %}">Editar</a></td>
                                <td><a class="alert button" href="{% url 'coche_app:delete_coches' c.id %}">Eliminar</a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>

            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                            </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                            {% ifequal pagina page_obj.number %}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                            {% endifequal%}
                            
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                  </nav>
                {% endif %}
            </div>
        </div>
    </div>


{% endblock content%}

automoviles/templates/coche/register.html
{% extends 'base.html' %}

{% block title %}Registrar Coche{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Registrar nuevo Coche {{object.name}}</h1>
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Matricula:
                      {{form.matricula}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Fecha Fabricación:
                      {{form.fecha_creacion}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Marca:
                      {{form.marca}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Modelo:
                      {{form.modelo}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="submit success button">Registrar</button>
                </div>
                
            </form>
        </div>
    </div>
</div>
    
{% endblock content %}