automoviles/applications/marca/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "marca_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name="inicio"),
    path('lista-marcas/', views.ListMarcasListView.as_view(), name="list_marcas"),
    path('registrar-marca/', views.MarcaCreateView.as_view(), name="regist_marcas"),
    path('editar-marca/<pk>/', views.MarcaUpdateView.as_view(), name="edit_marcas"),
    path('eliminar-marca/<pk>/', views.MarcaDeleteView.as_view(), name="delete_marcas"),
]

automoviles/automoviles/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLS APPs
    re_path('', include('applications.marca.urls')),
    re_path('', include('applications.modelo.urls')),
    re_path('', include('applications.coche.urls'))
]

automoviles/applications/marca/models.py
from django.db import models
from .managers import MarcaManager

# Create your models here.

class Marca(models.Model):
    nombre = models.CharField('Marca', max_length=50, unique=True)
    fundador = models.CharField('Fundador', max_length=50)
    fecha_fundacion = models.DateField('Fundacion')
    telefono_atencion = models.IntegerField('Telefono', unique=True)
    modelos = models.ManyToManyField('modelo.Modelo', related_name='modelo',verbose_name='Modelos' , blank=True)

    objects = MarcaManager()

    class Meta:
        verbose_name = 'Marca'
        verbose_name_plural = 'Marcas'
        ordering = ['id']

    def __str__(self):
        return self.nombre

    def get_modelos(self):
        return " - ".join([str(p) for p in self.modelos.all()])

automoviles/applications/marca/forms.py
from django import forms

from .models import Marca

class MarcaForm(forms.ModelForm):
    
    class Meta:
        model = Marca
        fields = (
            'nombre',
            'fundador',
            'fecha_fundacion',
            'telefono_atencion',
            'modelos'
        )
        widgets = {
            'modelos': forms.SelectMultiple(),
            'fecha_fundacion': forms.DateInput(
                attrs= {
                    'placeholder': 'Dia/Mes/Año',
                }
            )
        }

automoviles/applications/marca/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from .models import Marca
from .forms import MarcaForm

class InicioView(TemplateView):
    template_name = 'inicio.html'

# Create your views here.
class ListMarcasListView(ListView):
    context_object_name = 'lista_marcas'
    template_name = 'marca/lista.html'
    paginate_by = 4

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        
        return Marca.objects.listar_marcas(palabra_clave)

class MarcaCreateView(CreateView):
    model = Marca
    template_name = "marca/register.html"
    form_class = MarcaForm
    success_url = reverse_lazy('marca_app:list_marcas')

    def form_valid(self, form):
        marca = form.save()
        marca.save()
        return super(MarcaCreateView, self).form_valid(form)

#UPDATE
class MarcaUpdateView(UpdateView):
    model = Marca
    template_name = "marca/editar.html"
    fields = [
        'nombre',
        'fundador',
        'fecha_fundacion',
        'telefono_atencion',
        'modelos'
    ]
    success_url = reverse_lazy('marca_app:list_marcas')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        #request.POST['name']
        return super().post(request, *args, **kwargs)

#DELETE
class MarcaDeleteView(DeleteView):
    model = Marca
    template_name = "marca/delete.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = reverse_lazy('marca_app:list_marcas')
        self.object.delete()
        return HttpResponseRedirect(success_url)

automoviles/templates/marca/delete.html
{% extends 'base.html' %}

{% block title %}Eliminar Marca{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Eliminar Marca {{object.nombre}}</h1>
            <div class="cell">
                <form class="cell" method="POST">{% csrf_token %}
                    <div class="callout secondary">
                        <h5>¿Desea eliminar esta marca?</h5>
                        <button type="submit" class="alert button">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}

automoviles/templates/marca/editar.html
{% extends 'base.html' %}

{% block title %}Editar Marca{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Editar Marca</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                    <div class="medium-6 cell">
                        <label>Marca:
                          {{form.nombre}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Fundador:
                          {{form.fundador}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Fecha Fundacion:
                          {{form.fecha_fundacion}}
                        </label>
                    </div>
                    <div class="medium-6 cell">
                        <label>Telefono Atencion al Cliente:
                          {{form.telefono_atencion}}
                        </label>
                    </div>
                    <div class="medium-12 cell">
                        <label>Modelos:
                          {{form.modelos}}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="submit success button">Actualizar</button>
                    </div>
                </form>                
            </div>
        </div>
    </div>
    
{% endblock content %}

automoviles/templates/marca/lista.html
{% extends 'base.html' %}

{% block title %}Lista Marcas{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Lista de Marcas</h1>
            <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7">
                    <input type="text" id="kword" name="kword" placeholder="Buscar Marca">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="submit success button">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="50">ID</th>
                        <th width="150">MARCA</th>
                        <th width="150">FUNDADOR</th>
                        <th width="150">FECHA FUNDACION</th>
                        <th width="150">TELEFONO ATENCION</th>
                        <th width="150">MODELOS</th>
                        <th width="10"></th>
                        <th width="10"></th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for m in lista_marcas %}
                            <tr>
                                <td>{{m.id}}</td>
                                <td>{{m.nombre}}</td>
                                <td>{{m.fundador}}</td>
                                <td>{{m.fecha_fundacion}}</td>
                                <td>{{m.telefono_atencion}}</td>
                                <td>{{m.get_modelos}}</td>
                                <td><a class="button warning" href="{% url 'marca_app:edit_marcas' m.id %}">Editar</a></td>
                                <td><a class="alert button" href="{% url 'marca_app:delete_marcas' m.id %}">Eliminar</a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>

            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{page_obj.previous_page_number}}">Atrás</a>
                            </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                            {% ifequal pagina page_obj.number %}
                                <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
                            {% else %}
                                <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                            {% endifequal%}
                            
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                  </nav>
                {% endif %}
            </div>

        </div>
    </div>


{% endblock content%}

automoviles/templates/marca/register.html
{% extends 'base.html' %}

{% block title %}Registrar Marca{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container" style="margin-top:50px;">
        <div class="grid-x">
            <h1 class="cell">Registrar nueva Marca {{object.name}}</h1>
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
                <div class="medium-6 cell">
                    <label>Marca:
                      {{form.nombre}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Fundador:
                      {{form.fundador}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Fecha Fundacion:
                      {{form.fecha_fundacion}}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>Telefono Atencion al Cliente:
                      {{form.telefono_atencion}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <label>Modelos:
                      {{form.modelos}}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="submit success button">Registrar</button>
                </div>
                
            </form>
        </div>
    </div>
</div>
    
{% endblock content %}